### ISSUE TITLE
Wrong generic type in AkitaFiltersPlugin?

### ISSUE THREAD

**Issue by chriszrc** [manudss/akita-filters-plugin#15]
I was able to get the filters plugin working, but I had to change the generic type in this section:

https://github.com/manudss/akita-filters-plugin/blob/98a61d684ecaad114033423ab39606965cb8016a/projects/akita-filters-plugin/src/lib/akita-filters-plugin.ts#L51-L60

To use `S` and not `E`, which makes sense (to me), since the akita QueryEntity should have a type that extends the EntityState, not the Entity itself, right?

https://netbasal.gitbook.io/akita/entity-store/entity-query

When I added this lib to my project, with entity type:

```
export interface DataTable {
  id: ID;
  column1: string|number;
  column2: string|number;
  column3: string|number;
  column4: string|number;
  column5: string|number;
}
```

and EntityState:

```
export interface DataTableState extends EntityState<DataTable>, MultiActiveState {
  ui: {
    colNames?: Map<string,string>;
    pageIndex?: number;
    pageSize?: number;
  };
}
```

and then tried adding the filter to my service:

```
export class DataTableService {
  filters: AkitaFiltersPlugin<DataTableState, DataTable>;

  constructor(
    private dataTableStore: DataTableStore,
    private dataTableQuery: DataTableQuery,
  ){
    this.filters = new AkitaFiltersPlugin<DataTableState, DataTable>(dataTableQuery);
  }
```

I would get an error:

```
Argument of type 'DataTableQuery' is not assignable to parameter of type 'QueryEntity<DataTable, unknown, unknown>'. Types of property 'store' are incompatible. Type 'DataTableStore' is not assignable to type 'EntityStore<DataTable, unknown, unknown>'. ......
```

Which is technically correct, I'm passing in a QueryEntity of type `QueryEntity<DataTableState,unknown,unknown>` not `QueryEntity<DataTable, unknown, unknown>`. Changing `S` to `E` in the typings fixes my type error, and also lets everything work as expected. 

Is this a bug or something by design?

**Comment by manudss** [comment]
Hello, 

I will try to look at this. This was related that Akita change since this plugins has been created. Before, akita ask for both E and S. 

I will try to changes all, to have only S.

**Comment by chriszrc** [comment]
@manudss nice! thanks for the quick update!
