### ISSUE TITLE
AkitaFilter.predicate isn't persisted to localstorage, or included in getFilters()

### ISSUE THREAD

**Issue by chriszrc** [manudss/akita-filters-plugin#16]
I've got the filter plugin working in my app, and it's beautifully filtering an `AkitaMatDataSource`. When I change the filters, the table records update. However, I'm also trying to do two things that don't appear to work:

1 - using the `persistState()` (https://netbasal.gitbook.io/akita/enhancers/persist-state) so that state is saved across page refreshes 

2 - I need each entity in my own separate entity store to be able to store their own set of filters. So I use `getFilters()` to save a copy of the the current filters when they're updated, so I can restore an entire set of filters as the active entity changes in my entity store. 

In each case, either in local storate, or in redux tools, the filterstore shows the filters (and all their properties), but not the `predicate` property. 

Any ideas?

**Comment by manudss** [comment]
Hi, 

The predicate, could not be stored in local storage, this is a function. 
What you could do, is to create again the predicate function, when you get the changes from the localstorage. 

In the filter object, you can store any value you want. You can use this to store other value usefull for you, to know, how to create your predicate function. 

Hope this answer your question.

**Comment by chriszrc** [comment]
@manudss Hi, thanks, this makes sense, I actually had never tried to persist a function, so I wasn't aware of this akita/localstorage limitation. I'm taking your advice to recreate the predicate function. Seems like the `preStoreUpdate` hook in the persistState plugin is ideal for this. 

I do see now that the AkitaFilter technically allows you to store any value you want, since it adds this field:

```
/** add any other data you want to add **/
    [key: string]: any;
```

I do wonder however if there's any way to add this flexibility but preserve type safety? I already messed up the filter object names, and because any field is technically accepted, typescript didn't catch it. I created an interface that extends `AkitaFilter`, and that makes it a little better, but the type safety issue is still there :(

**Comment by manudss** [comment]
Hello, 

In typescript, if you declare a already existe type, it will be merge : https://www.typescriptlang.org/docs/handbook/declaration-merging.html 

But sometimes, you could have conflics with this. 

But if you have created an extended AkitaFilter type. You should cast it to this extended type, to use it. Like this : 

`const filterExtended : AkitaFilterExtended = (filter as AkitaFilterExtended)`

Regards.

**Comment by chriszrc** [comment]
Hi, 

That's an interesting idea, but as long as the `[key: string]: any;` is present on the AkitaFilter interface, any property name will still be valid, which kinda defeats the typechecking. Currently, I'm just extending the filter:

```
export interface AkitaFilterDataTable extends AkitaFilter<DataTableState> {
  columnName: string,
  //...etc
```

Which works totally fine, given that the akita filter code is setup to store whatever object it gets. I just wonder if there's a way to continue supporting that, while not adding a blanket property like `[key: string]: any;`, which makes it so any property is valid, and therefore, when I write:

```
this.dataTableService.upsertFilter({
     columnNOTRIGHTName: 'etc',
     //...etc
})
```

I don't get an error

**Comment by chriszrc** [comment]
@manudss I was able to successfully extend and store the filters and recreate them after they were persisted to localstorage. But it's only working for copies I'm storing in each of enitites of the set of filters. The actual filter store appears to be totally cleared out after I refresh the project, even though the values have been successfully serialized to localstorage. Any ideas?
