### ISSUE TITLE
Is there a synchronous "get" version of selectAllByFilters()?

### ISSUE THREAD

**Issue by chriszrc** [manudss/akita-filters-plugin#17]
I found this a bit unintuitive, since typical akita query classes expose both a `select` and a `get` method so we can either retrieve an observable and raw value, respectively. The easiest workaround is also a little tricky, because this:

```
let filteredTableData = await this.dataTableService.filters.selectAllByFilters().toPromise();
```

Will never return a value, because the observable never completes (which is what we normally want). It took me a few minutes that I needed to add `take(1)`, so the observable would complete:

```
let filteredTableData = await this.dataTableService.filters.selectAllByFilters().pipe(
   take(1)
).toPromise();
```

Which works just fine, but I think it would be better all around to have a synchronous method option for querying the filters entity store.

**Comment by manudss** [comment]
Hi Chris, 

I will take a look when I have time to do this. Or you can propose a PR, if you want !

**Comment by manudss** [comment]
Hi Chris,

I have finally released a new version that introduce, this feature in version 6.0.0. (Just released 2 of may).

Sorry for the long time, to do this request.
