### ISSUE TITLE
Question: Using a join on a select

### ISSUE THREAD

**Issue by ShaneC112** [manudss/akita-filters-plugin#18]
How can I get the AkitaMatDataSource filter query to refer to a specific query from in the store.
I just can't figure it out !!

Taking the below as an example (https://netbasal.gitbook.io/akita/angular/architecture).
The join is working but only when selectItems$ is called.
The filter does not show the additional values as it is using selectAll. 
How can it be changed to use selectItem$ and include the additional information.

Thanks
Shane

PS Thanks for fixing the other bug so quickly was greatly appreciated.

import { combineLatest } from 'rxjs';
import { map } from 'rxjs/operators';

@Injectable({ providedIn: 'root' })
export class CartQuery extends QueryEntity<CartState> {
  constructor(protected store: CartStore, 
              private productsQuery: ProductsQuery) {
    super(store);
  }

  selectItems$ = combineLatest([
     this.selectAll(), 
     this.productsQuery.selectAll({ asObject: true })
   ]
  ).pipe(map(joinItems));
}

function joinItems([cartItems, products]: [CartItem[], Product[]]) {
  return cartItems.map(item => {
    const product = products[item.productId];
    return {
      ...item,
      ...product,
      total: item.quantity * product.price
    };
  });
}

**Comment by manudss** [comment]
Hi Shane, 

If I understood correctly, you wants to update the selectAll method, with other information. 

Maybe, you could use overinding methode. 

In Akiata data source, you can provide the query, and akitaFiltersPlugins in the contructor. 

You can update your query, to override  selectAll function 
```typescript
selectAll(options: SelectAllOptionsA): Observable<HashMap>> {
    return combineLatest([
      super.selectAll(options),
        this.productsQuery.selectAll({ asObject: true })
      ]
    ).pipe(map(joinItems));
  }
```

Or also do the same for akitaPlugins. 

```typescript
class CustomFiltersPlugins extends AkitaFiltersPlugin {     
      constructor() {
        super(CartQuery, {filtersStoreName: 'CustomFilters'});
      }

    selectAllByFilters(options: any): Observable<HashMap>> {
        return combineLatest([
               super.selectAllByFilters(options),
              this.productsQuery.selectAll({ asObject: true })
            ]
          ).pipe(map(joinItems));
     }
   }
```
and then create your akita data source by giving the your akita filters plugin :

`this.dataSource = new AkitaMatDataSource(cartQuery, customFiltersPlugins);`

Not tested theses sollutions, but should works. 

That answer to your question ? and your needs ? 

Don't hesitate to keep me posted, if it works for you?
