### ISSUE TITLE
AkitaMatDataSource Sort or Paginator don't work on Angular 9

### ISSUE THREAD

**Issue by FerdyGood** [manudss/akita-filters-plugin#20]
Since I upgraded my app to Angular 9, I get the following build error:

Type 'import(".../node_modules/@angular/material/sort/sort").MatSort' is not assignable to type 'import(".../node_modules/akita-filters-plugin/node_modules/@angular/material/sort/typings/sort").MatSort'.
      Types have separate declarations of a private property '_direction'.

The same goes wrong for the Paginator:

Type 'import(".../node_modules/@angular/material/paginator/paginator").MatPaginator' is not assignable to type 'import(".../node_modules/@angular/material/paginator/typings/paginator").MatPaginator'.
      Types have separate declarations of a private property '_changeDetectorRef'.

**Comment by manudss** [comment]
Hi, 

Their is some problem to import this two MatSort and MatPaginator. While both seens not to use the same between the library and the another project. 

I need to find how to correct this. But before you could use workaround : 

use ts ignore, to ignore error. 
 `// @ts-ignore 
this.dataSource.paginator = this.paginator; `

or put your local variable as any. 
`  @ViewChild(MatPaginator, { static: true }) paginator: any;`

This would works until I could correct this. 

Sorry about that.
