### ISSUE TITLE
why has akita-filter-plugin @angular/material as dependency

### ISSUE THREAD

**Issue by ejthan** [manudss/akita-filters-plugin#22]
since i installed akita-filter-plugin, i get many error messages because of angular/material. The versions angular/cdk and angular/material do not match. Since I am not using angular material in my project -> is there a way out?

**Comment by manudss** [comment]
Hi 
Can you show me, the error ?

Normally, Angular material was using only for "AkitaMatDataSource". If you don't have Material, you should not use this page.

**Comment by ejthan** [comment]
I did not use AkitaMatDataSource...

`ERROR in node_modules/@angular/material/core/common-behaviors/common-module.d.ts(8,10): error TS2305: Module '"node_modules/@angular/cdk/a11y"' has no exported member 'HighContrastModeDetector'.
node_modules/@angular/material/core/datetime/date-adapter.d.ts(29,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/core/option/optgroup.d.ts(8,10): error TS2305: Module '"node_modules/@angular/cdk/coercion"' has no exported member 'BooleanInput'.
node_modules/@angular/material/core/option/option.d.ts(8,10): error TS2305: Module '"node_modules/@angular/cdk/coercion"' has no exported member 'BooleanInput'.
node_modules/@angular/material/core/option/option.d.ts(51,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/core/option/option.d.ts(53,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/core/option/option.d.ts(59,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/core/option/option.d.ts(60,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/core/option/option.d.ts(62,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/core/option/option.d.ts(74,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/core/option/option.d.ts(79,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/core/ripple/ripple.d.ts(60,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/core/ripple/ripple.d.ts(61,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/core/ripple/ripple.d.ts(67,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/core/ripple/ripple.d.ts(68,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/core/ripple/ripple.d.ts(85,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/core/ripple/ripple.d.ts(90,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/paginator/paginator.d.ts(8,10): error TS2305: Module '"node_modules/@angular/cdk/coercion"' has no exported member 'BooleanInput'.
node_modules/@angular/material/paginator/paginator.d.ts(8,24): error TS2305: Module '"node_modules/@angular/cdk/coercion"' has no exported member 'NumberInput'.
node_modules/@angular/material/paginator/paginator.d.ts(59,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/paginator/paginator.d.ts(60,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/paginator/paginator.d.ts(63,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/paginator/paginator.d.ts(64,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/paginator/paginator.d.ts(67,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/paginator/paginator.d.ts(68,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/paginator/paginator.d.ts(71,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/paginator/paginator.d.ts(72,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/paginator/paginator.d.ts(75,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/paginator/paginator.d.ts(76,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/paginator/paginator.d.ts(79,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/paginator/paginator.d.ts(80,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/sort/sort-header.d.ts(8,10): error TS2305: Module '"node_modules/@angular/cdk/coercion"' has no exported member 'BooleanInput'.
node_modules/@angular/material/sort/sort-header.d.ts(88,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/sort/sort-header.d.ts(89,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/sort/sort.d.ts(8,10): error TS2305: Module '"node_modules/@angular/cdk/coercion"' has no exported member 'BooleanInput'.
node_modules/@angular/material/sort/sort.d.ts(47,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/sort/sort.d.ts(48,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/sort/sort.d.ts(54,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/material/sort/sort.d.ts(55,9): error TS1086: An accessor cannot be declared in an ambient context.`

**Comment by ejthan** [comment]
npm ls @angular/material shows:
`-- akita-filters-plugin@3.0.2
  `-- @angular/material@9.1.3

**Comment by datasage** [comment]
In relation to this, shouldn't the @angular/material and @angular/cdk packages be set as peerDependencies?

Anyone who is going to be using likely already has it installed, everyone else can avoid downloading it into node_modules.
