### ISSUE TITLE
Question: Filtering with normalized data

### ISSUE THREAD

**Issue by FerdyGood** [manudss/akita-filters-plugin#28]
The API I'm using, returns data in a normalized way: (short version)

Products: [
  {
    id: guid,
    supplier: guid
  }
]

Suppliers: [
  {
    id: guid,
    name: string
  }
]

They are both stored in their separate stores.

Is there a way (with the filters plugin) where I can filter Products, with predicate something like:
product => product.supplier.name.includes(<some string>)

**Comment by manudss** [comment]
Hi,

You will need to conbine all your request like explained here : https://netbasal.com/working-with-normalized-data-in-akita-e626d4c67ca4 

So For Akita Filters plugins, use the selectAll function from one Query Class. 

But you can override the selectAll Function, to add your combineFunction, something like this. 

```typescript

export class TodosQuery extends QueryEntity<TodosState> {
  constructor(protected store: TodosStore) {
    super(store);
  }
  selectAll(options?: { asObject, filterBy, limitTo, sortBy, sortByOrder }) {
     return super.selectAll(options).pipe(map(data => { /** get all your normalized data **/}));
 }
}
```
Does this answer to your question ?

**Comment by FerdyGood** [comment]
I have to play with this a little, but I think I can make this work! Thanks!
