### ISSUE TITLE
Cannot find module 'akita-filters-plugins/datasource'

### ISSUE THREAD

**Issue by ejthan** [manudss/akita-filters-plugin#42]
I know have a project in which we would like to use AkitaMatDataSource, but i get the error:
Cannot find module 'akita-filters-plugins/datasource'

this is how i imported the AkitaMatDataSource:
`import { AkitaMatDataSource } from 'akita-filters-plugins/datasource';`

Version installed is: 4.1.0-beta.1

With regard to server-side pagination, I'm still not sure whether I should use the akita-filters-plugin variant or the PaginatorPlugin, is there a recommendation? 
Currently we use the akita-filters-plugin with the withServer function and would like to add server-side pagination.

**Comment by manudss** [comment]
Hello,

Great to use this plugins.

It strange that you have this error, I use it for several projects, and for us it's working. 
What is your versions for all your project ? Angular, typescript etc... ?

For pagination in server side, I plan to do this, but I didn't take the time to do this.

But if you would like to make a Pull request, your welcome to do this. Else I will see if I could works on this at the end of the month.

Regards,

**Comment by ejthan** [comment]
currently we are using the following versions:
`"typescript": "~3.9.5"
"@angular/core": "~10.0.3"
"tslib": "^2.0.0"`

**Comment by manudss** [comment]
@ejthan  Sorry for the delay, I was in holiday. I found your problems. Their is a typo remove "s" in akita-filters-plugin, you need import like this : 

`import { AkitaMatDataSource } from 'akita-filters-plugin/datasource'; `

**Comment by ejthan** [comment]
@manudss thanks for the help.

Pagination:
unfortunately, i think my coding skills are not good enough to help you with a pull request
i can try but you have to point me to the right direction...
