### ISSUE TITLE
Custom Sorting with AkitaMatDataSource 

### ISSUE THREAD

**Issue by lilas78** [manudss/akita-filters-plugin#47]
When using a MatDataSource, we have the possibility to customize the sorting by defining a "sortingDataAccessor" : this way, we can sort not on object attribute value, but on a custom computed value. This can be useful when a data column of a MatTable shows a computed value.
How can we accomplish this with a AkitaMatDataSource ?
With a AkitaMatDataSource, the sorting works great when the value of a column corresponds to an object attribute. But I don't find the way to define a sorting callback to customize the sorting behavior when the column value doesn't correspond to an object attribute.

I tried with hints gave in [link](https://github.com/datorama/akita/issues/581), but with no success.

Do you thing you could add this function "sortingDataAccessor"?

Thank you

**Comment by manudss** [comment]
Hello @lilas78, 

Sorry to did not answer. Yes I will take a look, to add this function.
