### ISSUE TITLE
build error with last version of angular / material

### ISSUE THREAD

**Issue by freddez** [manudss/akita-filters-plugin#56]
Hello, I have this error when building my app with your package. I'm using last version of akita and angular material.

```
Error: node_modules/akita-filters-plugin/datasource/lib/akita-mat-data-source.d.ts:8:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (akita-filters-plugin/datasource) which declares AkitaMatDataSource has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

8 export declare class AkitaMatDataSource<S extends EntityState = any, E = getEntityType<S>> extends DataSource<E> {
                       ~~~~~~~~~~~~~~~~~~
```

**Comment by manudss** [comment]
Hi, 
I will try to update all angular library with new version, I hope this will resolve the error. 

Emmanuel

**Comment by freddez** [comment]
Nice !
I've tried to upgrade angular version in the example,

**Comment by freddez** [comment]
Sorry, closed by mistake

**Comment by manudss** [comment]
Hi @freddez 

I have updated to last version of Angular. Could you test, and let me know if this correct your problem. 

Thanks,

**Comment by freddez** [comment]
Hello @manudss , sorry but I still have the same error in my project (I've made a fresh reinstall).

**Comment by freddez** [comment]
Hi @manudss , do you manage to reproduce the problem ?

**Comment by manudss** [comment]
Hello @freddez,

Sorry, I haven't had much time to work on it this week. 
But I just did a test of a simple external project, with the latest versions of the packages. and I have no problem. 

Can you give me a version that has this problem, or more information on how you use all this.

**Comment by freddez** [comment]
Hello @manudss , I've generated a project with ng new, added angular material akita and akita filter plugin  and added akita filter in angular.app.js :

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { AkitaFiltersPlugin } from 'akita-filters-plugin';
import { NG_ENTITY_SERVICE_CONFIG } from '@datorama/akita-ng-entity-service';
import { AkitaNgDevtools } from '@datorama/akita-ngdevtools';
import { AkitaNgRouterStoreModule } from '@datorama/akita-ng-router-store';
import { environment } from '../environments/environment';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    BrowserAnimationsModule,
    AkitaFiltersPlugin,
    environment.production ? [] : AkitaNgDevtools.forRoot(),
    AkitaNgRouterStoreModule,

  ],
  providers: [{ provide: NG_ENTITY_SERVICE_CONFIG, useValue: { baseUrl: 'https://jsonplaceholder.typicode.com' }}],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

And I have the error :
```
    ERROR in node_modules/akita-filters-plugin/lib/akita-filters-plugin.d.ts:22:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

    This likely means that the library (akita-filters-plugin) which declares AkitaFiltersPlugin has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

    22 export declare class AkitaFiltersPlugin<S extends EntityState, E = getEntityType<S>, I = OrArray<getIDType<S>>, P = any> extends EntityCollectionPlugin<S, P> {
                            ~~~~~~~~~~~~~~~~~~
```

**Comment by manudss** [comment]
Hello @freddez , 

Sorry for the response time to help you, but I was having a hard time understanding why there was this problem. Especially since I had tried like you to make a new project and build it. But it was working very well for me, and I didn't have that problem too. 

But I think I understand the problem: Why you want to import the AkitaFiltersPlugins into your module. This plugin is absolutely not an angular module. It's just a service. So you have to create it by making new AkitaFiltersPlugins() or a class that extends AkitaFiltersPlugins. 

So I think, it's just enough for you to remove the import in your module, and it should work. 

Can you try it and confirm me that this is it. Thanks in advance.

**Comment by freddez** [comment]
Oh, my mistake ! Sorry, it works, thank you for for help @manudss
