### ISSUE TITLE
Paginator Record Total not showing on Material Data table with AkitaDataSource

### ISSUE THREAD

**Issue by ShaneC112** [manudss/akita-filters-plugin#8]
On the demo project the number of page number and total number of pages are not shown.
Is there a quick fix for this. I have the same problem in my project.

Pagination is working just not showing.

Many Thanks

![image](https://user-images.githubusercontent.com/5805863/69857813-f7c9a780-1290-11ea-93f1-bec485b4ac63.png)

**Comment by ShaneC112** [comment]
As a workaround 

    <mat-paginator #paginator [pageIndex]="0" [pageSize]="10" [pageSizeOptions]="[10,25, 50, 100, 250]" [length]="(datasource?.selectCount | async)">
    </mat-paginator>

**Comment by manudss** [comment]
@ShaneC112 I have made a correction. It will be available in the next release. 2.1.3. 

Could you check that it correct the bug for you, and let me know. 

Thanks for your reports, and using this libs.
